#!/bin/bash

get_next_command() {
    command=$(cat $stack_path | tail -n 1)
    echo $command
}

is_stack_empty() {
    command=$(get_next_command)
    if [[ $command == "" ]]; then
        return 1
    else
        return 0
    fi
}

terminate() {
    ./$1 finalise
    exit $2
}

# The minimum amount of RAM (in KB) required to store the next command to run
# NOTE: A non-empty text file with only ASCII characters using UTF-8 will use n+1 bytes where n is the number of characters
min_ram_req=50 # TODO: Figure out a value for this

# Get the amount of unallocated space in RAM (in KB)
ram_unallocated=($(df /dev/shm/ | tail -n 1))
ram_unallocated=${ram_unallocated[3]}

# Figure out whether to store in memory or on disk
stack_base_path=""
if [[ $ram_unallocated > $min_ram_req ]]; then
    stack_base_path="/dev/shm/"
else
    stack_base_path="/tmp/"
fi

# Get a new path to the stack head
stack_id=$(uuidgen)
stack_base_path=$stack_base_path"osman-"$stack_id
stack_path=$stack_base_path".bash"

# Run the manager UI
manager="OSManager.CLI/bin/Debug/net8.0/OSManager.CLI"
# ./$manager initialise --stack $stack_base_path --slave $manager
./$manager initialise --stack $stack_base_path --slave $manager --workingdir $HOME/Projects/package-configs

# Run any subsequent commands
is_stack_empty
last_command=""
while [[ $? == 0 ]] ; do
    command=$(get_next_command)

    if [[ $last_command == $command ]]; then
        if [[ $command == "" ]]; then
            echo "Reached end of commands. Exiting..."
        else
            echo "Something is wrong, received the same command twice. Exiting..."
        fi
        terminate $manager 1
    fi

    eval $command

    if [[ $? != 0 ]]; then
        break
    fi

    last_command=$command
    is_stack_empty
done

terminate $manager 0
